# Generated by Django 3.1.7 on 2021-04-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(db_index=True, max_length=50)),
                ('lastname', models.CharField(db_index=True, max_length=60)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('message', models.TextField(blank=True, db_index=True)),
                ('response', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_image', models.CharField(db_index=True, max_length=50)),
                ('image', models.ImageField(upload_to='main/media/gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_team', models.CharField(db_index=True, max_length=50)),
                ('image_team', models.ImageField(upload_to='main/media/image_team')),
                ('image_car', models.ImageField(upload_to='main/media/car_team')),
                ('pilot1', models.CharField(db_index=True, max_length=50)),
                ('pilot2', models.CharField(db_index=True, max_length=50)),
                ('age1', models.IntegerField(default=0)),
                ('age2', models.IntegerField(default=0)),
                ('birthday1', models.CharField(db_index=True, max_length=30)),
                ('birthday2', models.CharField(db_index=True, max_length=30)),
                ('body', models.TextField(blank=True, db_index=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
